{% set name = "pydaymet" %}
{% set version = "0.11.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydaymet-{{ version }}.tar.gz
  sha256: ac46d8dea11afd989cc4391338dff1881218d1f1a15e7085039beb167b81089f

build:
  number: 0
  noarch: python
  entry_points:
    - pydaymet = pydaymet.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - async_retriever >=0.2
    - click
    - dask-core
    - lxml
    - numpy >=1.17
    - pandas >=1.0
    - py3dep >=0.11.3
    - pydantic
    - pygeoogc >=0.11.5
    - pygeoutils >=0.11.5
    - python >=3.7
    - rasterio >=1.2
    - scipy
    - shapely >=1.6
    - xarray >=0.17

test:
  imports:
    - pydaymet
  commands:
    - pip check
    - pydaymet --help
  requires:
    - pip

about:
  home: https://github.com/cheginit/pydaymet
  summary: Access the climate data from the Daymet database through its RESTful service.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
