{% set name = "pydaymet" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9f373826e11dd1298da4a7ce83fed09125151446ab8294948baf3dd5cf0e5246

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - setuptools
    - py3dep
    - lxml
    - dask

test:
  imports:
    - pydaymet

about:
  home: https://github.com/cheginit/pydaymet
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Access the climate data from the Daymet database through ORNL's RESTful service.

  description: |
    PyDaymet is a part of Hydrodata software stack that provides access to the Daymet's climate
    data through ORNL's RESTful service.
  doc_url: https://hydrodata.readthedocs.io
  dev_url: https://github.com/cheginit/pydaymet

extra:
  recipe-maintainers:
    - cheginit
