{% set name = "pydaymet" %}
{% set version = "0.10.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydaymet-{{ version }}.tar.gz
  sha256: b44d23e9837b739fff4cf978d8d98a57fd2c6d19d51e2dabe134654595ece1d9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - aiodns
    - aiohttp
    - brotlipy
    - chardet
    - cytoolz
    - dask-core
    - defusedxml
    - geopandas
    - lxml
    - nest-asyncio
    - netcdf4
    - orjson
    - owslib
    - py3dep
    - pygeoogc
    - pygeoutils
    - pyproj
    - python >=3.6
    - rasterio
    - requests
    - scipy
    - setuptools
    - shapely
    - simplejson
    - xarray

test:
  imports:
    - pydaymet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/pydaymet
  summary: Access the climate data from the Daymet database through its RESTful service.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
