{% set name = "pydaymet" %}
{% set version = "0.12.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydaymet-{{ version }}.tar.gz
  sha256: edf81daecc504934b97c14bb20c17b7d4684f8ca6006ca04459c120296859fa6

build:
  number: 0
  noarch: python
  entry_points:
    - pydaymet = pydaymet.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - async_retriever >=0.3.1
    - click
    - dask-core
    - lxml
    - numpy >=1.17
    - pandas >=1.0
    - py3dep >=0.12.2
    - pydantic
    - pygeoogc >=0.12.2
    - pygeoutils >=0.12.2
    - python >=3.7
    - rasterio >=1.2
    - scipy
    - shapely >=1.6
    - xarray >=0.18
    - importlib_metadata

test:
  imports:
    - pydaymet
  commands:
    - pip check
    - pydaymet --help
  requires:
    - pip

about:
  home: https://github.com/cheginit/pydaymet
  summary: Access the climate data from the Daymet database through its RESTful service.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
