{% set name = "pydaymet" %}
{% set version = "0.13.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydaymet-{{ version }}.tar.gz
  sha256: 0c418e3f1edb3c78a4ae0cda68716726f19c7e097b712dc64aec382d68ee8d57

build:
  entry_points:
    - pydaymet = pydaymet.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools-scm
  run:
    - python >=3.8
    - async-retriever >=0.3.8
    - click >=0.7
    - dask-core
    - lxml
    - numpy >=1.17
    - pandas >=1.0
    - py3dep >=0.13.8
    - pygeoogc >=0.13.8
    - pygeoutils >=0.13.10
    - rasterio >=1.2
    - scipy
    - shapely >=1.8
    - xarray >=2022.03.0

test:
  imports:
    - pydaymet
  commands:
    - pip check
    - pydaymet --help
  requires:
    - pip

about:
  home: https://github.com/hyriver/pydaymet
  summary: Access daily, monthly, and annual climate data via the Daymet web service.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
