{% set name = "pydaymet" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydaymet-{{ version }}.tar.gz
  sha256: 53d92903581fa4546630c1c2aeb5d9e1960f45f2a2fde5eac2aa6e218020b775

build:
  number: 0
  noarch: python
  entry_points:
    - pydaymet = pydaymet.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - async_retriever
    - click
    - dask-core
    - lxml
    - numpy
    - pandas
    - py3dep
    - pydantic
    - pygeoogc
    - pygeoutils
    - python >=3.7
    - rasterio
    - scipy
    - shapely
    - xarray

test:
  imports:
    - pydaymet
  commands:
    - pip check
    - pydaymet --help
  requires:
    - pip

about:
  home: https://github.com/cheginit/pydaymet
  summary: Access the climate data from the Daymet database through its RESTful service.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
