{% set name = "pydaymet" %}
{% set version = "0.13.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydaymet-{{ version }}.tar.gz
  sha256: 50a6068719ff0d7707ee5b63501db23ceb85863daf0d862547888f9572f06eda

build:
  entry_points:
    - pydaymet = pydaymet.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools-scm
  run:
    - python >=3.8
    - pygeoutils >=0.13.5
    - scipy
    - async_retriever >=0.3.5
    - rasterio >=1.2
    - xarray >=2022.03.0
    - pandas >=1.0
    - py3dep >=0.13.5
    - numpy >=1.17
    - pydantic
    - pygeoogc >=0.13.5
    - click >=0.7
    - shapely >=1.8
    - dask-core
    - lxml

test:
  imports:
    - pydaymet
  commands:
    - pip check
    - pydaymet --help
  requires:
    - pip

about:
  home: https://github.com/hyriver/pydaymet
  summary: Access daily, monthly, and annual climate data via the Daymet web service.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
