{% set name = "pydaymet" %}
{% set version = "0.13.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydaymet-{{ version }}.tar.gz
  sha256: 85876e0cf170105f22903531762a2b117f6f8ade4297e9c06182a6160057fdd7

build:
  number: 0
  noarch: python
  entry_points:
    - pydaymet = pydaymet.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - async_retriever >=0.3.2
    - click
    - dask-core
    - lxml
    - numpy >=1.17
    - pandas >=1.0
    - py3dep >=0.13.2
    - pydantic
    - pygeoogc >=0.13.2
    - pygeoutils >=0.13.2
    - python >=3.8
    - rasterio >=1.2
    - scipy
    - shapely >=1.7
    - xarray >=0.18

test:
  imports:
    - pydaymet
  commands:
    - pip check
    - pydaymet --help
  requires:
    - pip

about:
  home: https://github.com/cheginit/pydaymet
  summary: Access the climate data from the Daymet database through its RESTful service.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
