{% set name = "pydaymet" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydaymet-{{ version }}.tar.gz
  sha256: 4983853c336a383ca16d498b6d67977a2cc6ff9de65ed140091bec07f218e9e8

build:
  entry_points:
    - pydaymet = pydaymet.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm >=7
    - pip
  run:
    - python >=3.8
    - async-retriever <0.16,>=0.15
    - click >=0.7
    - dask-core
    - geopandas >=0.10
    - lxml
    - numpy >=1.21
    - pandas >=1.0
    - py3dep <0.16,>=0.15
    - pygeoogc <0.16,>=0.15
    - pygeoutils <0.16,>=0.15
    - pyproj >=3.0.1
    - rasterio >=1.2
    - rioxarray >=0.11
    - scipy
    - shapely >=1.8.5
    - xarray >=2023.04.0

test:
  imports:
    - pydaymet
  commands:
    - pip check
    - pydaymet --help
  requires:
    - pip

about:
  home: https://github.com/hyriver/pydaymet
  summary: Access daily, monthly, and annual climate data via the Daymet web service.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
