{% set name = "pydaymet" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydaymet-{{ version }}.tar.gz
  sha256: 20f00ba3297b7dfeab2b409615d4438d1139a5b7e3442c39401730fb0b2d0ccb

build:
  entry_points:
    - pydaymet = pydaymet.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools-scm
  run:
    - python >=3.8
    - async-retriever >=0.3.12
    - click >=0.7
    - dask-core
    - geopandas >=0.10
    - lxml
    - numpy >=1.21
    - pandas >=1.0
    - py3dep >=0.13.12
    - pygeoogc >=0.13.12
    - pygeoutils >=0.13.12
    - pyproj >=2.2
    - rasterio >=1.2
    - scipy
    - shapely >=1.8
    - xarray >=2022.03.0

test:
  imports:
    - pydaymet
  commands:
    - pip check
    - pydaymet --help
  requires:
    - pip

about:
  home: https://github.com/hyriver/pydaymet
  summary: Access daily, monthly, and annual climate data via the Daymet web service.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
