{% set name = "pydaymet" %}
{% set version = "0.11.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydaymet-{{ version }}.tar.gz
  sha256: af69d4d15bcfdff09a11b1711e925e1fc7cb7ca75b3c790fe348d5427719417b

build:
  number: 0
  noarch: python
  entry_points:
    - pydaymet = pydaymet.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - async_retriever >=0.2
    - click
    - dask-core
    - lxml
    - numpy >=1.17
    - pandas >=1.0
    - py3dep
    - pydantic
    - pygeoogc >=0.11
    - pygeoutils >=0.11
    - python >=3.7
    - rasterio
    - scipy
    - shapely >=1.6
    - xarray >=0.17

test:
  imports:
    - pydaymet
  commands:
    - pip check
    - pydaymet --help
  requires:
    - pip

about:
  home: https://github.com/cheginit/pydaymet
  summary: Access the climate data from the Daymet database through its RESTful service.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
