{% set name = "pydaymet" %}
{% set version = "0.15.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydaymet-{{ version }}.tar.gz
  sha256: 60921b0e4aa9c8e535acb93fce47ca393537481e36d04950e81de3832c6f2261

build:
  entry_points:
    - pydaymet = pydaymet.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm >=7
    - pip
  run:
    - python >=3.8
    - async-retriever <0.16,>=0.15
    - click >=0.7
    - dask-core
    - geopandas >=0.10
    - lxml
    - numpy >=1.21
    - pandas >=1.0
    - py3dep <0.16,>=0.15.1
    - pygeoogc <0.16,>=0.15.1
    - pygeoutils <0.16,>=0.15
    - pyproj >=3.0.1
    - rasterio >=1.2
    - rioxarray >=0.11
    - scipy
    - shapely >=1.8.5
    - xarray >=2023.04.0

test:
  imports:
    - pydaymet
  commands:
    - pip check
    - pydaymet --help
  requires:
    - pip

about:
  home: https://github.com/hyriver/pydaymet
  summary: Access daily, monthly, and annual climate data via the Daymet web service.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
